[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    #"RUSTSEC-0000-0000",
]
# * None - CVSS Score 0.0
# * Low - CVSS Score 0.1 - 3.9
# * Medium - CVSS Score 4.0 - 6.9
# * High - CVSS Score 7.0 - 8.9
# * Critical - CVSS Score 9.0 - 10.0
severity-threshold = "High"

[licenses]
default = "deny"
copyleft = "deny"
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "ISC",
]
allow-osi-fsf-free = "neither"
confidence-threshold = 0.8
exceptions = [
    { name = "wolfssl", allow = ["GPL-2.0"], version = "*" },
    { name = "wolfssl-sys", allow = ["GPL-2.0"], version = "*" },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
skip = [
    { name = "bindgen", version = "0.68.1" },
    { name = "bitflags", version = "1.3.2" },
    { name = "windows-sys", version = "0.48.0" },
    { name = "windows-targets", version = "0.48.5" },
    { name = "windows_aarch64_gnullvm", version = "0.48.5" },
    { name = "windows_aarch64_msvc", version = "0.48.5" },
    { name = "windows_i686_gnu", version = "0.48.5" },
    { name = "windows_i686_msvc", version = "0.48.5" },
    { name = "windows_x86_64_gnu", version = "0.48.5" },
    { name = "windows_x86_64_gnullvm", version = "0.48.5" },
    { name = "windows_x86_64_msvc", version = "0.48.5" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
