name: Nightly `cargo deny` checks
on:
  schedule:
    - cron:  '24 12 * * *'
  workflow_dispatch:

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: EmbarkStudios/cargo-deny-action@v1
